using Microsoft.Extensions.Hosting;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace IGLib.Core
{


    /// <inheritdoc/>
    public class ModelParameter : IModelParameter
    {

        /// <summary>Comprehensive constructor, initializes all fields of the type.</summary>
        /// <param name="name">Name of the current model parameter, as is used in models
        /// (defines the <see cref="Name"/>) property.</param>
        /// <param name="type">Type of the current parameter (defines the <see cref="Type"/> property)</param>
        /// <param name="title">Title for parameter description, defines the <see cref="Title"/> property.
        /// If null (but not if empty string) then title is generated by the <see cref="DefaultRitle(string)"/> method.</param>
        /// <param name="description">Parameter description, defines the <see cref="Description"/> property.</param>
        /// <param name="defaultValue">Default value of the parameter, defines the <see cref="DefaultValueObject"/> property.</param>
        /// <param name="value">Value of the parameter, defines the <see cref="ValueObject"/> property.</param>
        /// <param name="isConstant">Whether the constructed parameter object represents a constant parameter. Optional, 
        /// default is <see cref="DefaultIsConstant"/>.</param>
        /// <param name="isDefaultWhenValueNotDefined">Specifies whether default value can be returned as value when
        /// the value is not defined but the default value is. Optional, default is <see cref="DefaultIsDefaultWhenValueNotDefined"/>.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public ModelParameter(string name, Type type, string title, string description = null,
            object defaultValue = null, object value = null,
            bool isConstant = DefaultIsConstant,
            bool isDefaultWhenValueNotDefined = ModelParameter.DefaultIsDefaultWhenValueNotDefined)
        {
            if (string.IsNullOrEmpty(name))
            {
                if (Name == null)
                {
                    throw new ArgumentNullException(nameof(name), "Parameter name cannot be null.");
                }
                throw new ArgumentException("Parameter name cannot be an empty string.", nameof(name));
            }
            if (Type == null)
            {
            }
            Name = name;
            Type = type;
            Title = title;
            if (Title == null)
            {
                Title = DefaultTitle(name);
            }
            Description = description;
            if (Description == null)
            {
                Description = DefaultDescription(name, type);
            }
            DefaultValueObject = defaultValue;
            ValueObject = value;
            IsConstant = isConstant;
            IsDefaultWhenValueNotDefined = isDefaultWhenValueNotDefined;
        }

        /// <summary>Minimal constructor that only defines parameter's name and type, and some flags with default
        /// values such tha these flags can be either specified or omitted (if defults are OK).
        /// <para>Meaning and behavior of parameters is the same as with 
        /// <see cref="ModelParameter(string, Type, string, string, object, object, bool, bool)"/>.</para></summary>
        public ModelParameter(string name, Type type,
            bool isConstant = DefaultIsConstant,
            bool isDefaultWhenValueNotDefined = DefaultIsDefaultWhenValueNotDefined) : 
            this(name, type, null, null, isConstant, isDefaultWhenValueNotDefined)
        {
            DefaultValueObject = null;  // this will also set IsDefaultValueDefined to false
            ValueObject = null;  // this will also set IsValueDefined to false
        }

        /// <summary>A terse constructor that also defines the default value, beside name and type, and some flags 
        /// with default values such tha these flags can be either specified or omitted (if defults are OK).</summary>
        public ModelParameter(string name, Type type, object defaultValue,
            bool isConstant = DefaultIsConstant,
            bool isDefaultWhenValueNotDefined = ModelParameter.DefaultIsDefaultWhenValueNotDefined) : this(name, type, 
            DefaultTitle(name), DefaultDescription(name, type), 
            isConstant, isDefaultWhenValueNotDefined)
        {
            DefaultValueObject = defaultValue;  // this will also set IsDefaultValueDefined to true if not null
            ValueObject = null;  // this will also set IsValueDefined to false
        }

        /// <summary>Generates default title of the parameter object when title is not defined, using
        /// parameter's name. Used in constructors.</summary>
        /// <param name="name">Name of the parameter, used to generate its title.</param>
        protected static string DefaultTitle(string name) => $"Parameter {name}";

        /// <summary>Generated default description of the parameterr object when it is not defined, using
        /// parameter's name and type.</summary>
        /// <param name="name">Name of the parameter, used to generate its description.</param>
        /// <param name="type">Type of the parameter, used to generate its description.</param>
        protected static string DefaultDescription(string name, Type type)
            => $"Represents model parameter {name} of type ${type.Name}.";

        /// <summary>Default value of the property <see cref="IModelParameter.IsDefaultWhenValueNotDefined"/>,
        /// such that default initialization can be unified across implementations of <see cref="IModelParameter"/>.</summary>
        public const bool DefaultIsDefaultWhenValueNotDefined = true;

        /// <summary>Default value of the property <see cref="IModelParameter.IsConstant"/>,
        /// such that default initialization can be unified across implementations of <see cref="IModelParameter"/>.</summary>
        public const bool DefaultIsConstant = false;

        /// <summary>Default initial value of the property <see cref="IModelParameter.IsDefaultValueDefined"/>,
        /// such that default initialization can be unified across implementations of <see cref="IModelParameter"/>.</summary>
        public const bool InitialIsDefaultValueDefined = false;

        /// <summary>Default initial value of the property <see cref="IModelParameter.IsValueDefined"/>,
        /// such that default initialization can be unified across implementations of <see cref="IModelParameter"/>.</summary>
        public const bool InitialIsValueDefined = false;

        /// <inheritdoc/>
        public string Name { get; init; }

        /// <inheritdoc/>
        public virtual Type Type { get; init; }

        /// <inheritdoc/>
        public string Title { get; protected set; }

        /// <inheritdoc/>
        public string Description { get; protected set; }
        private object _defaultValueObject = null;

        /// <inheritdoc/>
        public virtual object DefaultValueObject 
        {
            get
            {
                if (IsDefaultValueDefined)
                {
                    return _defaultValueObject;
                }
                throw new InvalidOperationException($"Default value of parameter {Name} is not defined.");
            }
            protected set
            {
                if (IsConstant && IsDefaultValueDefined)
                {
                    throw new InvalidOperationException($"Cannot redefine default value of parameter {Name} because it is constant.");
                }
                _defaultValueObject = value;
                if (value != null)
                {
                    IsDefaultValueDefined = true;
                }
                else
                {
                    IsDefaultValueDefined = false;
                }
            }
        }

        /// <inheritdoc/>
        public virtual bool IsDefaultValueDefined { get; protected set; } = InitialIsValueDefined;

        private object _valueObject = null;

        /// <inheritdoc/>
        public virtual object ValueObject 
        {
            get
            {
                if (IsValueDefined)
                {
                    return _valueObject;
                }
                if (IsDefaultWhenValueNotDefined && IsDefaultValueDefined)
                {
                    // When value is not defined, we can replace it by the default value:
                    return DefaultValueObject;
                }
                // Could not get the value, therefore throw:
                if (IsDefaultWhenValueNotDefined)
                {
                    throw new InvalidOperationException($"Value of parameter {Name} is not defined, and default value is also not defined.");
                }
                throw new InvalidOperationException($"Value of parameter {Name} is not defined and it is not replaceable by its default value.");
            }
            set
            {
                if (IsConstant && IsValueDefined)
                {
                    throw new InvalidOperationException($"Can not redefine value of parameter {Name} because it is constant.");
                }
                _valueObject = value;
                if (value != null)
                {
                    IsValueDefined = true;
                }
                else
                {
                    IsValueDefined = false;
                }
            }
        }

        /// <inheritdoc/>
        public virtual bool IsValueDefined { get; protected set; } = InitialIsValueDefined;

        /// <inheritdoc/>
        public virtual bool IsDefaultWhenValueNotDefined { get; protected set; } 
            = DefaultIsDefaultWhenValueNotDefined;

        public virtual bool IsConstant { get; init; } = DefaultIsConstant;

        /// <inheritdoc/>
        public virtual IModelParameter ClearValue()
        {
            ValueObject = default;
            IsValueDefined = false;
            return this;
        }

        /// <inheritdoc/>
        public virtual IModelParameter UpdateValue(object newValue)
        {
            ValueObject = newValue;
            return this;
        }

        /// <inheritdoc/>
        public virtual IModelParameter ClearDefaultValue()
        {
            DefaultValueObject = default;
            IsDefaultValueDefined = false;
            return this;
        }

        /// <inheritdoc/>
        public virtual IModelParameter UpdateDefaultValue(object newDefaultValue)
        {
            DefaultValueObject = newDefaultValue;
            return this;
        }

        /// <inheritdoc/>
        public virtual IModelParameter UpdateTitle(string newTitle)
        {
            Title = newTitle;
            return this;
        }

        /// <inheritdoc/>
        public virtual IModelParameter UpdateDescription(string newDescription)
        {
            Description = newDescription;
            return this;
        }



        /// <inheritdoc/>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.AppendLine($"Model parameterr ${Name} (${Type.Name}):");
            sb.AppendLine($"  Title: \"{Title}\"");
            sb.AppendLine($"  Description: \"{Description}\"");
            sb.AppendLine($"  Default value: {(DefaultValueObject == null ? "null" : DefaultValueObject.ToString())}");
            // sb.AppendLine($"  Value: {(IsValueDefined ? (ValueObject == null ? "null" : ValueObject.ToString()) : "<Not defined.>")}");
            sb.AppendLine($"  Value: {(ValueObject == null ? "null" : ValueObject.ToString())}");
            sb.AppendLine($"  Is value defined: {IsValueDefined}");
            return sb.ToString();
        }

        /// <summary>Creates a sample <see cref="ModelParameter"/> object, prints its content to console,
        /// and returns it.</summary>
        internal static ModelParameter CreateExampleParameter1()
        {
            ModelParameter param = new ModelParameter("Param1", typeof(double))
            {
                Title = "Parameter Φ1, phase shift in the first direction.",
                Description = "This parameter of type double specifies the phase shift of the 3D Lissajous curve in the direction x.",
                DefaultValueObject = (double)0,
                IsValueDefined = false
            };
            Console.WriteLine($"Created {param.GetType()} ojbject:\n{param.ToString()}");
            return param;
        }

    }

}
